name: Release, publish npm package & deploy Storybook

on:
  release:
    types: [published]

permissions:
  contents: write   # нужно для загрузки ассетов в релиз

env:
  STORYBOOK_PREVIEW_BASE: "/var/www/storybook/data"
  STORYBOOK_URL_BASE: "https://storybook.triplex-dev.ru"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci
      - run: npm run build

      # ---- Упаковать dist в архив для ассетов релиза ----
      - name: Create dist.zip
        run: |
          zip -r "dist-${{ github.event.release.tag_name }}.zip" dist

      # ---- Публикация в npm ----
      - name: Publish to npm
        run: npm publish --access public ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # ---- Загрузка dist.zip (и, при желании, .tgz) в ассеты релиза ----
      - name: Upload build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-${{ github.event.release.tag_name }}.zip
            # *.tgz

      # ---- Сборка и деплой Storybook ----
      - name: Build Storybook
        run: npm run storybook:build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STORYBOOK_SSH_PRIVATE_KEY }}

      - name: Deploy Storybook to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STORYBOOK_SSH_USER }} "mkdir -p $STORYBOOK_PREVIEW_BASE/releases/${{ github.event.release.tag_name }}"
          rsync -avz --delete storybook-static/ ${{ secrets.STORYBOOK_SSH_USER }}:$STORYBOOK_PREVIEW_BASE/releases/${{ github.event.release.tag_name }}/

      - name: Output Storybook URL
        run: echo "Storybook deployed ${{ env.STORYBOOK_URL_BASE }}/releases/${{ github.event.release.tag_name }}"